project_name                 = ""
region                       = ""
environment                  = ""
vpc_cidr_block               = ""
route_destination_cidr_block = ""
sg_cidr_blocks_inbound       = ""
sg_cidr_blocks_outbound      = ""
pub_subnet_cidr              = ""
priv_subnet_cidr             = ""
pub_zone                     = ""
priv_zone                    = ""

ami                          = ""
instance_type                = ""
